CREATE DATABASE IF NOT EXISTS ShopEasy;

USE ShopEasy;

CREATE TABLE RUOLO (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE CATEGORIA (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE UTENTE (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  cognome VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  indirizzo VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  language_preference ENUM('IT', 'EN') NOT NULL DEFAULT 'IT',
  theme_preference ENUM('LIGHT', 'DARK') NOT NULL DEFAULT 'LIGHT',
  ruolo ENUM('UTENTE', 'ADMIN') DEFAULT 'UTENTE',
  stato ENUM('ATTIVO', 'DISABILITATO') NOT NULL DEFAULT 'ATTIVO',
  FOREIGN KEY (ruolo) REFERENCES RUOLO(id)
);

CREATE TABLE PRODOTTO (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  descrizione TEXT,
  prezzo DECIMAL(10, 2) NOT NULL,
  quantita BIGINT DEFAULT 0,
  immagine VARCHAR(255),
  categoria_id BIGINT,
  FOREIGN KEY (categoria_id) REFERENCES CATEGORIA(id)
);

CREATE TABLE ORDINE (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  data DATETIME DEFAULT CURRENT_TIMESTAMP,
  totale DECIMAL(10, 2) NOT NULL,
  stato ENUM(
    'ORDINATO',
    'CANCELLATO',
    'IN_CONSEGNA',
    'CONSEGNATO'
  ) NOT NULL,
  utente_id BIGINT,
  FOREIGN KEY (utente_id) REFERENCES UTENTE(id)
);

CREATE TABLE DETTAGLIO_ORDINE (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  prodotto_id BIGINT NOT NULL,
  ordine_id BIGINT NOT NULL,
  quantita BIGINT NOT NULL,
  prezzo DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (prodotto_id) REFERENCES PRODOTTO(id),
  FOREIGN KEY (ordine_id) REFERENCES ORDINE(id)
);

CREATE TABLE WISHLIST (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  utente_id BIGINT NOT NULL UNIQUE,
  FOREIGN KEY (utente_id) REFERENCES UTENTE(id)
);

CREATE TABLE WISHLIST_PRODOTTO (
  wishlist_id BIGINT NOT NULL,
  prodotto_id BIGINT NOT NULL,
  PRIMARY KEY (wishlist_id, prodotto_id),
  FOREIGN KEY (wishlist_id) REFERENCES WISHLIST(id) ON DELETE CASCADE,
  FOREIGN KEY (prodotto_id) REFERENCES PRODOTTO(id) ON DELETE CASCADE
);

CREATE TABLE STATISTICHE (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  fatturato_totale BIGINT DEFAULT 0,
  visualizzazioni BIGINT DEFAULT 0,
  utenti_registrati BIGINT DEFAULT 0,
  ordini_totali BIGINT DEFAULT 0,
  prodotti_totali BIGINT DEFAULT 0
  
);
