spring.application.name=shopeasy

#  DATABASE - PostgreSQL
spring.datasource.url=jdbc:postgresql://develop.rjcsoft.it:5432/shopeasy
spring.datasource.username=shopeasy_user
spring.datasource.password=Yy2TGkkg2qG6kenah7
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER
server.port=8080

#INVIO EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shopeasy749@gmail.com
spring.mail.password=mmglkhxpknqalwyw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#DURATA TOKEN EMAIL
app.reset-token-expiration=30